# Generated by Django 4.0.4 on 2023-04-01 17:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Concelho')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[200, 200], upload_to='county/images/', verbose_name='Imagem')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='county/covers/', verbose_name='Imagem de capa')),
                ('description_pt', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Português)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Inglês)')),
                ('date_founded', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('vidId', models.CharField(blank=True, max_length=150, null=True, verbose_name='Id de Video')),
            ],
            options={
                'verbose_name': 'Concelho',
                'verbose_name_plural': 'Concelhos',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Comida')),
                ('description_pt', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Português)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Inglês)')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='food/images/', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Foto')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='gallery/', verbose_name='Imagem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galeria',
            },
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Freguesia')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[200, 200], upload_to='parish/images/', verbose_name='Imagem')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[200, 200], upload_to='parish/covers/', verbose_name='Imagem de capa')),
                ('description_pt', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Português)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Inglês)')),
                ('date_founded', models.DateField(blank=True, null=True, verbose_name='Data de Fundação')),
                ('vidId', models.CharField(blank=True, max_length=150, null=True, verbose_name='Id de Video')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.county', verbose_name='Concelho')),
                ('gallery', models.ManyToManyField(blank=True, to='core.imagegallery')),
            ],
            options={
                'verbose_name': 'Freguesia',
                'verbose_name_plural': 'Freguesias',
            },
        ),
        migrations.CreateModel(
            name='PlaceCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_pt', models.CharField(max_length=150, null=True, verbose_name='Categoria(Português)')),
                ('categorie_en', models.CharField(max_length=150, null=True, verbose_name='Categoria(Inglês)')),
            ],
            options={
                'verbose_name': 'Categoria de Locais',
                'verbose_name_plural': 'Categorias de Locais',
            },
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_pt', models.CharField(max_length=150, verbose_name='Tag(Português)')),
                ('tag_en', models.CharField(max_length=150, verbose_name='Tag(Inglês)')),
            ],
            options={
                'verbose_name': 'Tag para local',
                'verbose_name_plural': 'Tags para Locais',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[200, 200], upload_to='users/profile/', verbose_name='Foto de Perfil')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Morada')),
                ('zip_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='Código Postal')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cidade')),
                ('verified', models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='Verificado')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategorie_pt', models.CharField(max_length=150, null=True, verbose_name='Sub Categoria(Português)')),
                ('subcategorie_en', models.CharField(max_length=150, null=True, verbose_name='Sub Categoria(Inglês)')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.placecategorie', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria de Locais',
                'verbose_name_plural': 'Subcategorias de Locais',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('stars', models.IntegerField(blank=True, null=True, verbose_name='Estrelas(Se for Hotel)')),
                ('description_pt', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Português)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Inglês)')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1024, 768], upload_to='places/images')),
                ('cover', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='places/covers')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Morada')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='Código Postal')),
                ('map_lat', models.CharField(blank=True, max_length=150, null=True, verbose_name='Latitude(Mapa)')),
                ('map_long', models.CharField(blank=True, max_length=150, null=True, verbose_name='Longitude(Mapa)')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('trip_advisor', models.URLField(blank=True, null=True, verbose_name='Trip Advisor')),
                ('booking', models.URLField(blank=True, null=True, verbose_name='Booking')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('vidId', models.CharField(blank=True, max_length=150, null=True, verbose_name='Id de Video(Youtube)')),
                ('published', models.CharField(blank=True, default=0, max_length=1, null=True, verbose_name='Publicado')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.placesubcategorie', verbose_name='Categoria')),
                ('food', models.ManyToManyField(blank=True, to='core.food', verbose_name='Comida(Se for restaurante)')),
                ('gallery', models.ManyToManyField(blank=True, to='core.imagegallery')),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parish', verbose_name='Freguesia')),
                ('tag', models.ManyToManyField(blank=True, to='core.placetag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Ilha')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[200, 200], upload_to='islands/images/', verbose_name='Imagem')),
                ('cover', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=85, scale=None, size=[1920, 1080], upload_to='islands/covers/', verbose_name='Imagem de Capa')),
                ('description_pt', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Português)')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição(Inglês)')),
                ('vidId', models.CharField(blank=True, max_length=150, null=True, verbose_name='Id de Video')),
                ('gallery', models.ManyToManyField(blank=True, to='core.imagegallery')),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='core.imagegallery'),
        ),
        migrations.AddField(
            model_name='county',
            name='gallery',
            field=models.ManyToManyField(blank=True, to='core.imagegallery'),
        ),
        migrations.AddField(
            model_name='county',
            name='island',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.island', verbose_name='Ilha'),
        ),
    ]
